shop/accounts/api/v1/urls.py
from django.urls import path
from .views import (
    UserListApiView,
    UserProfileListApiView,
    UserUpdateApiView,
    UserCreateApiView,
    UserDeleteApiView,
    UserProfileDeleteApiView,
    UserProfileUpdateApiView,
    UserDetailApiView,
    ProfileDetailApiView,
    LoginApiView,
    UserOrderFilterApiView,
    UserIsCompleteApiView,
    UserCityFilterApiView, 
    UserMaxAgeApiView,
    UserMinAgeApiView, 
    UserNameSearchApiView,
    UserDateJoinedApiView,
)


urlpatterns = [
    # List
    path("users-list/", UserListApiView.as_view()),
    path("users-profile/", UserProfileListApiView.as_view()),
    # Detail
    path("users-detail/<int:pk>/", UserDetailApiView.as_view()),
    path("users-profile-detail/<int:pk>/", ProfileDetailApiView.as_view()),
    # Update
    path("users-change-info/<int:pk>/", UserUpdateApiView.as_view()),
    path("users-change-profile/<int:pk>/", UserProfileUpdateApiView.as_view()),
    # Create
    path("users-create/", UserCreateApiView.as_view()),
    # Delete
    path("users-delete/<int:pk>/", UserDeleteApiView.as_view()),
    path("users-profile-delete/<int:pk>/", UserProfileDeleteApiView.as_view()),
    # Login
    path("login/", LoginApiView.as_view(), name="login-api"),
    # User Filters
    path("user-order/", UserOrderFilterApiView.as_view()),
    path("user-complete/", UserIsCompleteApiView.as_view()),
    path("user-city/", UserCityFilterApiView.as_view()),
    path("user-max-age/", UserMaxAgeApiView.as_view()),
    path("user-min-age/", UserMinAgeApiView.as_view()),
 
    path("users/search/username/", UserNameSearchApiView.as_view()), # Params /?name=user_name
    path("users/filter/created/", UserDateJoinedApiView.as_view()), # Params /?date=
]

shop/accounts/urls.py
from django.urls import path, include
from accounts.views import (
    SignUpView,
    LoginUserView,
    UserLogOutView,
    UserProfileView,
    ProfileUpdateView,
    UserChangePasswordView,
    UserAddressView,
    UserOrderView,
)


app_name = "accounts"

urlpatterns = [
    path("register/", SignUpView.as_view(), name="signup1"),
    path("login/", LoginUserView.as_view(), name="signin1"),
    path("logout/", UserLogOutView.as_view(), name="logout"),
    path("profile/", UserProfileView.as_view(), name="profile1"),
    path("profile/update/", ProfileUpdateView.as_view(), name="update1"),
    path("change-password/", UserChangePasswordView.as_view(), name="change1"),
    path("address/", UserAddressView.as_view(), name="address1"),
    path("orders/", UserOrderView.as_view(), name="order1"),
    # API
    path("api/v1/", include("accounts.api.v1.urls")),
]

shop/blog/urls.py
from django.urls import path, include
from blog.views import (
    BlogPageView,
    BlogDetailView,
    CategoryDetailView,
)

app_name = "blog"

urlpatterns = [
    path("", BlogPageView.as_view(), name="bloglist1"),
    path("<slug:slug>/", BlogDetailView.as_view(), name="blogdetail1"),
    path(
        "category/<slug:slug_cat>/",
        CategoryDetailView.as_view(),
        name="category_detail",
    ),
    # API
    path("api/v1/", include("blog.api.v1.urls")),
]

shop/shop/urls.py
from django.urls import path, include
from shop.views import (
    ShopListView,
    ShopDetailView,
    SearchView,
    CategoryListView,
    CategoryDetailView,
    CheckOutView,
)

app_name = "shop"

urlpatterns = [
    path("", ShopListView.as_view(), name="shoplist"),
    path("search/", SearchView.as_view(), name="search1"),
    path("product/<slug:slug>/", ShopDetailView.as_view(), name="detailpro"),
    path("all-categories/", CategoryListView.as_view(), name="categorylist1"),
    path("<str:category_slug>/", CategoryDetailView.as_view(), name="categorydetail1"),
    path("payment/checkout/", CheckOutView.as_view(), name="checkout1"),
    path("api/v1/", include("shop.api.v1.urls")),
]

shop/shopproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from rest_framework_simplejwt.views import (
    # TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

schema_view = get_schema_view(
    openapi.Info(
        title="Massay API",
        default_version="v1",
        description="This is a Massay Api page",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="mehdipoladrag1382@gmail.com"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("admin/", admin.site.urls),
    # Doc Routs
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
   
    # Django Apps 
    path("", include("home.urls")),
    path("shop/", include("shop.urls")),
    path("accounts/", include("accounts.urls")),
    path("contact-us/", include("contact.urls")),
    path("blog/", include("blog.urls")),
    path("cart/", include("cart.urls")),
    path("admin-panel/", include("adminpanel.urls")),
    path("api-auth/", include("rest_framework.urls")),

    # Default Api Routs
    # path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/accounts/models.py
import uuid
from django.db import models
from django.utils.translation import gettext as _
from django.contrib.auth.models import AbstractUser


# Create your models here.


class CustomUser(AbstractUser):
    id = models.AutoField(primary_key=True)
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    username = models.CharField(max_length=150, unique=True)


class CustomProfileModel(models.Model):
    GENDER_CHOICES = (
        (False, "مرد"),
        (True, "زن"),
    )
    user = models.OneToOneField(
        CustomUser, on_delete=models.CASCADE, verbose_name="نام کاربری", related_name="profile"
    )
    national_code = models.CharField(_("کد ملی"), max_length=10)
    address = models.TextField(_("آدرس"), blank=True, null=True)
    zipcode = models.CharField(_("کد پستی"), max_length=20, blank=True, null=True)
    street = models.CharField(_("خیابان"), max_length=50, blank=True, null=True)
    city = models.CharField(_("شهر"), max_length=20, blank=True, null=True)
    mobile = models.CharField(_("موبایل"), max_length=11, blank=True, null=True)
    age = models.PositiveIntegerField(_("سن"), blank=True, null=True)
    gender = models.BooleanField(_("جنسیت"), choices=GENDER_CHOICES, default=False)
    card_number = models.CharField(
        _("شماره کارت"), max_length=16, blank=True, null=True
    )
    iban = models.CharField(_("شماره شبا"), max_length=16, blank=True, null=True)
    back_money = models.CharField(
        _("روش بازگشت پول"), max_length=50, default="شماره شبا", blank=True, null=True
    )
    customer_image = models.ImageField(
        _("عکس کاربر"), upload_to="images/profile/%Y/%m/%d", blank=True, null=True
    )
    is_complete = models.BooleanField(_("پروفایل تکمیل شده؟"), default=False)

    def __str__(self):
        return self.user.username
    
    def get_gender(self):
        return 'زن' if self.gender else 'مرد'

    class Meta:
        verbose_name = "پروفایل"
        verbose_name_plural = "پروفایل ها"

shop/accounts/api/v1/views.py
# Libraries
from rest_framework import generics
from rest_framework_simplejwt.authentication import JWTAuthentication 
from rest_framework.permissions import AllowAny, IsAdminUser
from drf_yasg.utils import swagger_auto_schema  # type: ignore
from drf_yasg import openapi  # type: ignore
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework_simplejwt.views import TokenObtainPairView
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from django.db.models import Q
from django.db.models import Max, Min
from datetime import datetime
# Modules
from .filters.user_join_filter import (
    UserProfileSearchFilter,
    UserOrderFilter,
    UserSearchFilter,
)
from .filters.max_user_order_filter import UserMaxOrderFilter
from accounts.models import CustomProfileModel, CustomUser
from .serializers import (
    UserSerializer,
    UserProfileSerializer,
    UserDataSerializer,
    UserProfileDataSerializer,
    CustomTokenObtainPairSerializer,
    UserOrderSerializer,
    UserCompleteSerializer,
    UserCitySerializer,
    UserPersonalInformationSerializer,
    UserAllInformationSerializers,
)
from shop.models import Order
from .filters.paginations import UserFilterResultPagination



class CustomTokenObtainPairView(TokenObtainPairView):
    serializer_class = CustomTokenObtainPairSerializer


class LoginApiView(APIView):
    """Login API View For authentication To a Panel Admin"""

    permission_classes = [AllowAny]

    @swagger_auto_schema(
        operation_summary="Login endpoint for obtaining tokens",
        operation_description="Authenticate user and obtain tokens.",
        request_body=openapi.Schema(
            type=openapi.TYPE_OBJECT,
            properties={
                "username": openapi.Schema(
                    type=openapi.TYPE_STRING, description="The username of the user"
                ),
                "password": openapi.Schema(
                    type=openapi.TYPE_STRING, description="The password of the user"
                ),
            },
            required=["username", "password"],
        ),
        responses={
            200: openapi.Response(
                description="Login successful, token returned.",
                schema=CustomTokenObtainPairSerializer(),
            ),
            401: openapi.Response(
                description="Authentication credentials were not provided."
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["Authentication"],
    )
    def post(self, request, *args, **kwargs):
        serializer = CustomTokenObtainPairSerializer(
            data=request.data, context={"request": request}
        )
        if serializer.is_valid():
            return Response(serializer.validated_data, status=status.HTTP_200_OK)
        else:
            return Response(serializer.errors, status=status.HTTP_401_UNAUTHORIZED)


# LIST DATA API


@method_decorator(never_cache, name="dispatch")
class UserListApiView(generics.ListAPIView):
    """The job of this class is to return the list of users"""

    queryset = CustomUser.objects.select_related().order_by("date_joined")
    serializer_class = UserSerializer
    permission_classes = [IsAdminUser]
    filter_backends = [UserOrderFilter, UserSearchFilter]


@method_decorator(never_cache, name="dispatch")
class UserProfileListApiView(generics.ListAPIView):
    """The job of this class is to return the list of users and profiles of each user"""

    queryset = CustomProfileModel.objects.all()
    serializer_class = UserProfileSerializer
    permission_classes = [IsAdminUser]
    filter_backends = [UserProfileSearchFilter]


# DELETE DATA API


class UserDeleteApiView(generics.DestroyAPIView):

    "Delete User API"

    queryset = CustomUser.objects.all()
    serializer_class = UserDataSerializer
    permission_classes = [IsAdminUser]
    lookup_field = "pk"

    @swagger_auto_schema(
        operation_summary="This is a endpoint for Delete User",
        operation_description="Delete UserInformation in this api",
        response={
            200: openapi.Response(
                description="Delete a UserProfile Information",
                schema=UserDataSerializer(),
            ),
            401: openapi.Response(
                description="Authentication credentials were not provided."
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["User Information"],
    )
    def delete(self, request, *args, **kwargs):
        return self.destroy(request)


class UserProfileDeleteApiView(generics.DestroyAPIView):

    "Delete Profile API"

    queryset = CustomProfileModel.objects.all()
    serializer_class = UserProfileDataSerializer
    lookup_field = "pk"
    permission_classes = [IsAdminUser]

    @swagger_auto_schema(
        operation_summary="This is a endpoint for Delete UserProfile",
        operation_description="Delete UserProfile Information in this api",
        response={
            200: openapi.Response(
                description="Delete a UserProfile Information",
                schema=UserProfileSerializer(),
            ),
            401: openapi.Response(
                description="Authentication credentials were not provided."
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["Profile Information"],
    )
    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


# UPDATE DATA API


class UserUpdateApiView(generics.UpdateAPIView):
    """
    A class to update where we can send
    our http request as Put or send a patch
    """

    queryset = CustomUser.objects.all()
    serializer_class = UserDataSerializer
    permission_classes = [IsAdminUser]
    lookup_field = "pk"

    @swagger_auto_schema(
        operation_summary="This is a endpoint for Update User",
        operation_description="Update UserInformation in this api",
        response={
            200: openapi.Response(
                description="Update User",
                schema=UserSerializer(),
            ),
            401: openapi.Response(
                description="Authentication credentials were not provided."
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["User Information"],
    )
    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    @swagger_auto_schema(
        operation_summary="This is a endpoint for Update User",
        operation_description="Update UserInformation in this api",
        response={
            200: openapi.Response(
                description="Update User",
                schema=UserSerializer(),
            ),
            401: openapi.Response(
                description="Authentication credentials were not provided."
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["User Information"],
    )
    def patch(self, request, *args, **kwargs):
        return self.partial_update(request, *args, **kwargs)


class UserProfileUpdateApiView(generics.UpdateAPIView):
    """
    A class to update where we can send
    our http request as Put or send a patch
    """

    queryset = CustomUser.objects.all()
    serializer_class = UserProfileDataSerializer
    permission_classes = [IsAdminUser]
    lookup_field = "pk"

    @swagger_auto_schema(
        operation_summary="This is a endpoint for Update UserProfile Information",
        operation_description="We can Update UserProfile Information in this api",
        response={
            200: openapi.Response(
                description="Update Profile User",
                schema=UserProfileSerializer(),
            ),
            401: openapi.Response(
                description="Authentication credentials were not provided."
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["Profile Information"],
    )
    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    @swagger_auto_schema(
        operation_summary="This is a endpoint for Update UserProfile Information",
        operation_description="We can Update UserProfile Information in this api",
        response={
            200: openapi.Response(
                description="Update Profile User",
                schema=UserProfileSerializer(),
            ),
            401: openapi.Response(
                description="Authentication credentials were not provided."
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["Profile Information"],
    )
    def patch(self, request, *args, **kwargs):
        return self.partial_update(request, *args, **kwargs)


# CREATE DATA API


class UserCreateApiView(generics.CreateAPIView):
    """
    CreateUser Api
    """

    queryset = CustomUser.objects.all()
    serializer_class = UserDataSerializer
    permission_classes = [IsAdminUser]

    @swagger_auto_schema(
        operation_summary="This is a endpoint for Create User",
        operation_description="Create User in this api",
        response={
            200: openapi.Response(
                description="Create a New User",
                schema=UserSerializer(),
            ),
            401: openapi.Response(
                description="Authentication credentials were not provided."
            ),

shop/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}ورود{% endblock title %}
{% block content %}



        <main class="wrapper default">
            <div class="container">
                <div class="row">
                    <div class="main-content login_content  col-12 col-md-7 col-lg-5 mx-auto">
                        <header class="card-header">
                            <h3 class="card-title"><span>ورود به حساب کاربری</span></h3>
                        </header>
                        <div class="login_box">
                         
                          
                            
                                <form method="post" action="#" novalidated>
                                    <div class="row">
                                        <div class="col-md-12 col-sm-12">
                                          {{form.as_p}}
                                    
                                        </div>
                                        <div class="col-6">
                                            <div class="form-account-agree">
                                                <label class="checkbox-form checkbox-primary">
                                                    <input type="checkbox" id="agree">
                                                    <span class="checkbox-check"></span>
                                                </label>
                                                <label for="agree"> مرا به خاطر بسپار</label>
                                            </div>
                                        </div>
                                        <div class="col-6">
                                            <a class="faramooshi" href="#">رمز عبور را فراموش کرده اید؟</a>
                                        </div>
                                        <div class="col-12 text--center">
                                            <button type="submit" class="btn big_btn btn-main-masai">ورود  </button>
                                        </div>
                                        <div class="col-12 footer_login_reg text--center">
                                            <p>
                                                <span>کاربر جدید هستید؟</span>
                                                 <a href="{% url 'accounts:signup1' %}" >ثبت نام</a>

                                            </p>

                                        </div>
                                        <div class="col-12 ">

                                        </div>
                                    </div>
                                    {% csrf_token %}
                                </form>
                           
                            
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock content %}

shop/accounts/templates/accounts/order_list.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% load jalali_tags %}
{% block title %}تاریخچه سفارشات شما{% endblock title %}
{% block content %}
            <main class="order-delivered default space-top-30">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-9 col-lg-8 col-md-12 order-2">
                            <div class="row">
                                <div class="col-lg-12">
                                    <header class="card-header">
                                        <h3 class="card-title"><span>سفارشات در جریان</span></h3>
                                    </header>
                                {% for order in orders %}
                                <div class="content-section default">
                                    <div class="row">
                                        <div class="col-md-12 col-sm-12 order_delivered_sec">
                                            <div class="profile-recent-fav-row">
                                                <div class="col-12">
                                                    <h4 class="profile-recent-fav-name">
                                                        <i class="fa fa-check-circle" aria-hidden="true"></i> تحویل داده شده
                                                    </h4>
                                                    <ul>
                                                        <li>
                                                            {{ order.order_date|to_jalali:'%y/%m/%d | %H:%M:%S'}}
                                                        </li>
                                                        <li>
                                                            کد سفارش <b>{{ order.id }}</b>
                                                        </li>
                                                        <li>
                                                            مجموع سبد <b>{{ order.total_cost|intcomma }} تومان</b>
                                                        </li>
                                                    </ul>
                                                    <h4 class="profile-recent-Club">
                                                        <i class="fa fa-gift" aria-hidden="true"></i> امتیاز مسای‌کلاب <b>10</b>
                                                    </h4>
                                                </div>
                                                <div class="col-12">
                                        
                                                    <div class="row">
                                              
                                                        {% for order_item in order.orderitem_set.all %}
                                                            <a href="{% url 'shop:detailpro' order_item.product.slug %}">
                                                                <img src="{{ order_item.product.pic.url }}" alt="عکس محصول">
                                                            </a>
                                                       {% endfor %}
                                                     
                                                        </div>
                                                 
                                                </div>
                                                <div class="col-12 text-left">
                                                    <a class="btn btn-main-masai">مشاهده فاکتور</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="profile-page-aside col-xl-3 col-lg-4 col-md-6 center-section order-1">
                            <div class="profile-card-1">
                                <!--image-->
                            <div class="img">
            {% if profile.customer_image %}
                <img src="{{profile.customer_image.url}}" />
            {% endif %}
                            </div>
                                <!--text-->
                                <div class="mid-section">
                                    <div class="name">{{ profile.user.username }}</div>
                                        <div class="description">
                                            <a href="#" class="btn btn-main-masai">افزایش موجودی</a>
                                            <a href="#" class="btn btn-second-masai">مسای کلاب</a>
                                        </div>
                                        <div class="line"></div>
                                        <div class="stats">
                                            <div class="stat">
                                                {{ orders.count }}
                                                <div class="subtext">سفارش‌ها</div>
                                            </div>
                                            <div class="stat">
                                                68
                                                <div class="subtext">تحویل داده</div>
                                            </div>
                                        </div>
                                </div>
                            </div>
                            <div class="profile-menu ">
                                {% include "partials/_profile.html" %}
                            </div>
                        </div>
                    </div>
                </div>
            </main>


{% endblock content %}

shop/accounts/templates/accounts/signuppage.html
{% extends "base.html" %}
{% load static %}
{% block title %}ثبت نام{% endblock title %}
{% block content %}

 <main class="wrapper default ">
        <div class="container">
            <div class="row">
                <div class="main-content login_content  col-12 col-md-7 col-lg-5 mx-auto ">
                    <header class="card-header">
                        <h3 class="card-title"><span>ایجاد به حساب کاربری</span></h3>
                    </header>
                    <div class="login_box">



                <form class="" method="POST" action="{% url 'accounts:signup1' %}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                        {{form.as_p}}
                        </div>

                        <div class="col-12">
                            <div class="form-account-agree">
                                <label class="checkbox-form checkbox-primary">
                                    <input type="checkbox" id="agree" name="agree">
                                    <span class="checkbox-check"></span>
      
                                </label>
                                <label for="agree">
                                    تمامی <a href="#">شرایط و قوانین</a> استفاده از سرویس‌های سایت مَسای را به دقت مطالعه کرده و با آنها موافقت کامل دارم 
                                </label>
                            </div>
                        </div>
                    
                        <div class="col-12 text--center">
                            <button type="submit" class="btn big_btn btn-main-masai">عضویت</button>
                        </div>
                        <div class="col-12 footer_login_reg text--center">
                            <p>
                                <span>قبلا ثبت نام کرده اید؟</span>
                                <a href="{% url 'accounts:signin1' %}">ورود</a>
                            </p>
                        </div>
                        <div class="col-12 ">

                        </div>
                    </div>
                </form>


                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

shop/accounts/templates/accounts/updateuser.html
{% extends "base.html" %}
{% load static %}
{% block title %}بروزرسانی پروفایل{% endblock title %}
{% block content %}
<main class="profile-user-page default space-top-30">
    <div class="container">
        <div class="row">
            <div class="main-content login_content col-xl-9 col-lg-8 col-md-8 order-2 mx-auto">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <header class="card-header">
                            <h3 class="card-title"><span>اطلاعات حساب شخصی</span></h3>
                        </header>
                        <div class="login_box">
                            <form class="" method="post" action="" enctype="multipart/form-data">
                                {{user_form.as_p}}
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <header class="card-header">
                            <h3 class="card-title"><span>اطلاعات حساب ضرروی</span></h3>
                        </header>
                        <div class="login_box">
                                <div class="row">
                                    <div class="col-md-12 col-sm-12">
                                        {{profile_form.as_p}}
                                    </div>
                                </div>
                                <div class="col-12 text--center">
                                    <button type="submit" class="btn big_btn btn-main-masai">ثبت اطلاعات کاربری  </button>
                                </div>
                                {% csrf_token %}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
</main>
{% endblock content %}