shop/blog/api/v1/urls.py
from django.urls import path
from .views import (
    BloglistMixinView,
    BlogDetailmixinView,
    CategoryBlogListmixinView,
    CategoryBlogDetailmixinView,
    VisitorBlogDetailmixinView,
    VisitorBlogListmixinView,
)

app_name = "api-v1"

urlpatterns = [
    # Blogs
    path("blog-list/", BloglistMixinView.as_view(), name="api-blog-list"),
    path("blog-detail/<pk>/", BlogDetailmixinView.as_view(), name="api-blog-detail"),
    # Categories
    path("category-list/", CategoryBlogListmixinView.as_view()),
    path("category-detail/<pk>/", CategoryBlogDetailmixinView.as_view()),
    # Visitors
    path("Visitor-list/", VisitorBlogListmixinView.as_view()),
    path("Visitor-detail/<pk>/", VisitorBlogDetailmixinView.as_view()),
]

shop/blog/urls.py
from django.urls import path, include
from blog.views import (
    BlogPageView,
    BlogDetailView,
    CategoryDetailView,
)

app_name = "blog"

urlpatterns = [
    path("", BlogPageView.as_view(), name="bloglist1"),
    path("<slug:slug>/", BlogDetailView.as_view(), name="blogdetail1"),
    path(
        "category/<slug:slug_cat>/",
        CategoryDetailView.as_view(),
        name="category_detail",
    ),
    # API
    path("api/v1/", include("blog.api.v1.urls")),
]

shop/home/urls.py
from django.urls import path
from home.views import (
    HomePageView,
    AboutPageView,
)

app_name = "home"

urlpatterns = [
    path("", HomePageView.as_view(), name="home1"),
    path("about-us", AboutPageView.as_view(), name="about1"),
]

shop/shopproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from rest_framework_simplejwt.views import (
    # TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

schema_view = get_schema_view(
    openapi.Info(
        title="Massay API",
        default_version="v1",
        description="This is a Massay Api page",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="mehdipoladrag1382@gmail.com"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("admin/", admin.site.urls),
    # Doc Routs
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
   
    # Django Apps 
    path("", include("home.urls")),
    path("shop/", include("shop.urls")),
    path("accounts/", include("accounts.urls")),
    path("contact-us/", include("contact.urls")),
    path("blog/", include("blog.urls")),
    path("cart/", include("cart.urls")),
    path("admin-panel/", include("adminpanel.urls")),
    path("api-auth/", include("rest_framework.urls")),

    # Default Api Routs
    # path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/blog/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from accounts.models import CustomUser


class Category_blog(models.Model):
    name = models.CharField(_("نام دسته بندی"), max_length=100)
    slug_cat = models.SlugField(_("یو ار ال دسته بندی"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "دسته بندی وبلاگ"
        verbose_name_plural = "دسته بندی وبلاگ ها"


class Blogs(models.Model):
    username = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, verbose_name="نام کاربری"
    )
    blog_name = models.CharField(_("نام وبلاگ"), max_length=100)
    blog_image = models.ImageField(_("عکس وبلاگ"), upload_to="blog_images/")
    category = models.ForeignKey(
        Category_blog, on_delete=models.CASCADE, verbose_name="دسته بندی وبلاگ"
    )
    blog_description = models.TextField(
        _("توضیحات وبلاگ"),
    )
    create_date = models.DateTimeField(_("زمان ساخت وبلاگ"), auto_now_add=True)
    update_date = models.DateTimeField(_("زمان ویرایش وبلاگ"), auto_now=True)
    slug = models.SlugField(_("یو ار ال وبلاگ"), unique=True)

    def __str__(self):
        return self.blog_name

    class Meta:
        verbose_name = "وبلاگ"
        verbose_name_plural = "وبلاگ ها"


class Visitor(models.Model):
    post = models.ForeignKey(Blogs, on_delete=models.CASCADE, verbose_name="وبلاگ")
    user = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, verbose_name="نشر دهنده توسط"
    )
    timestamp = models.DateTimeField(_("تاریخ ساخت"), auto_now_add=True)

    def __str__(self):
        return f"Visitor: {self.blogs_details}"

    class Meta:
        verbose_name = "بازدید کننده "
        verbose_name_plural = "بازدید کنندگان"

shop/blog/api/v1/views.py
from rest_framework import generics, mixins
from rest_framework.permissions import IsAdminUser
from blog.models import Blogs, Category_blog, Visitor
from .serializers import BlogsSerializer, CategoryBlogSerializer, VisitorSerializer
from drf_yasg.utils import swagger_auto_schema
from drf_yasg import openapi
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator

# Blog API


class BloglistMixinView(
    mixins.ListModelMixin, mixins.CreateModelMixin, generics.GenericAPIView
):
    """
    In this class we can get the list
    of blogs and also create a new blog
    """

    queryset = Blogs.objects.all()
    serializer_class = BlogsSerializer
    permission_classes = [IsAdminUser]

    @swagger_auto_schema(
        operation_summary="List of blogs",
        operation_description="Retrieve a list of all blogs available in the system.",
        responses={
            200: openapi.Response(
                description="List of blogs",
                schema=BlogsSerializer(many=True),
            ),
            401: openapi.Response(
                description="Authentication credentials were not provided."
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["Blog"],
    )
    @method_decorator(cache_page(60 * 30))  # Cache for 30 minutes
    # Cache With Cookies For Requested Url
    def get(self, request):
        return self.list(request)

    @swagger_auto_schema(
        operation_summary="Creates a blog",
        operation_description="This Endpoint Creates a blog",
        responses={
            201: openapi.Response(
                description="Blog Created",
                schema=BlogsSerializer(),
            ),
            401: openapi.Response(
                description="Authentication credentials were not provided."
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["Blog"],
    )
    def post(self, request):
        return self.create(request)


class BlogDetailmixinView(
    mixins.RetrieveModelMixin,
    mixins.UpdateModelMixin,
    mixins.DestroyModelMixin,
    generics.GenericAPIView,
):
    """
    In this class, we can read, delete, and edit the details of a blog
    """

    permission_classes = [IsAdminUser]
    queryset = Blogs.objects.all()
    serializer_class = BlogsSerializer

    @swagger_auto_schema(
        operation_summary="Detail a Blog",
        operation_description="This endpoint provides details of a blog with pk.",
        responses={
            200: openapi.Response(
                description="Blog information",
                schema=BlogsSerializer(),
            ),
            401: openapi.Response(
                description="Authentication credentials were not provided."
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["Blog"],
    )
    @method_decorator(cache_page(60 * 30))
    # Cache With Cookies For Requested Url
    def get(self, request, pk):
        return self.retrieve(request, pk)

    @swagger_auto_schema(
        operation_summary="Update a Blog",
        operation_description="This endpoint updates the information of a blog with pk.",
        responses={
            200: openapi.Response(
                description="Blog Successfully Updated",
                schema=BlogsSerializer(),
            ),
            401: openapi.Response(
                description="Authentication credentials were not provided."
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["Blog"],
    )
    def put(self, request, pk):
        return self.update(request, pk)

    @swagger_auto_schema(
        operation_summary="Delete a Blog",
        operation_description="This endpoint deletes a blog with pk.",
        responses={
            204: openapi.Response(description="Blog Successfully Deleted"),
            401: openapi.Response(
                description="Authentication credentials were not provided."
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["Blog"],
    )
    def delete(self, request, pk):
        return self.destroy(request, pk)


# Category Blog API


class CategoryBlogListmixinView(
    mixins.ListModelMixin, mixins.CreateModelMixin, generics.GenericAPIView
):
    """
    In this class we can get the list
    of Categories and also create a new blog
    """

    permission_classes = [IsAdminUser]
    queryset = Category_blog.objects.all()
    serializer_class = CategoryBlogSerializer

    @swagger_auto_schema(
        operation_summary="List of BlogCategory",
        operation_description="Retrieve a list of all BlogCategory available",
        responses={
            200: openapi.Response(
                description="List of blogs",
                schema=CategoryBlogSerializer(many=True),
            ),
            401: openapi.Response(
                description="Authentication credentials were not provided."
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["Blog Categories"],
    )
    @method_decorator(cache_page(60 * 30))
    # Cache With Cookies For Requested Url
    def get(self, request):
        return self.list(request)

    @swagger_auto_schema(
        operation_summary="Creates a BlogCategory",
        operation_description="This Endpoint Creates a BlogCategory",
        responses={
            201: openapi.Response(
                description="BlogCategory Created",
                schema=CategoryBlogSerializer(),
            ),
            401: openapi.Response(
                description="Authentication credentials were not provided."
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["Blog Categories"],
    )
    def post(self, request):
        return self.create()


class CategoryBlogDetailmixinView(
    mixins.RetrieveModelMixin,
    mixins.UpdateModelMixin,
    mixins.DestroyModelMixin,
    generics.GenericAPIView,
):
    """
    In this class, we can read and
    delete and edit the details of a Categories
    """

    permission_classes = [IsAdminUser]
    queryset = Category_blog.objects.all()
    serializer_class = CategoryBlogSerializer

    @swagger_auto_schema(
        operation_summary="Detail a BlogCategory",
        operation_description="This endpoint provides details of a BlogCategory with pk",
        responses={
            200: openapi.Response(
                description="BlogCategory information",
                schema=CategoryBlogSerializer(),
            ),
            401: openapi.Response(
                description="Authentication credentials were not provided"
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["Blog Categories"],
    )
    @method_decorator(cache_page(60 * 30))
    # Cache With Cookies For Requested Url
    def get(self, request, pk):
        return self.retrieve(request, pk)

    @swagger_auto_schema(
        operation_summary="Update a BlogCategory",
        operation_description="This endpoint updates the information of a BlogCategory with pk",
        responses={
            200: openapi.Response(
                description="BlogCategory Successfully Updated",
                schema=CategoryBlogSerializer(),
            ),
            401: openapi.Response(
                description="Authentication credentials were not provided"
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["Blog Categories"],
    )
    def put(self, request, pk):
        return self.update(request, pk)

    @swagger_auto_schema(
        operation_summary="Delete a BlogCategory",
        operation_description="This endpoint deletes a BlogCategory with pk",
        responses={
            204: openapi.Response(description="BlogCategory Successfully Deleted"),
            401: openapi.Response(
                description="Authentication credentials were not provided"
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["Blog Categories"],
    )
    def delete(self, request, pk):
        return self.destroy(request, pk)


# VISITOR BLOG API


class VisitorBlogListmixinView(
    mixins.ListModelMixin, mixins.CreateModelMixin, generics.GenericAPIView
):
    """
    In this class we can get the list
    of Visitor and also create a new blog
    """

    permission_classes = [IsAdminUser]
    queryset = Visitor.objects.all()
    serializer_class = VisitorSerializer

    @swagger_auto_schema(
        operation_summary="Visitor Count Or List",
        operation_description="This is a endpoint for Visitor List",
        responses={
            204: openapi.Response(description="Visitor List "),
            401: openapi.Response(
                description="Authentication credentials were not provided"
            ),
            403: openapi.Response(description="Permission denied."),
        },
        tags=["Visitor Blogs"],
    )
    def get(self, request):
        return self.list(request)

    @swagger_auto_schema(
        operation_summary="Create a Visitor",
        operation_description="This Endpoint Creates a Visitor",
        responses={
            201: openapi.Response(
                description="Visitor Created",
                schema=BlogsSerializer(),
            ),
            401: openapi.Response(
                description="Authentication credentials were not provided"

shop/blog/views.py
from django.views.generic import ListView, DetailView, View
from django.shortcuts import render, get_object_or_404
from blog.models import Category_blog, Blogs
from django.core.paginator import Paginator

# Create your views here.


# Class Base View
class BlogPageView(ListView):
    template_name = "blog/blogpage.html"
    paginate_by = 1
    model = Blogs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["bloglist"] = Blogs.objects.all().order_by("create_date")
        context["categories"] = Category_blog.objects.all()
        return context


class BlogDetailView(DetailView):
    model = Blogs
    template_name = "blog/blogdetail.html"
    slug_url_kwarg = "slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        slug = self.kwargs[self.slug_url_kwarg]
        context["blogdetail"] = Blogs.objects.get(slug=slug)
        context["categories"] = Category_blog.objects.all()
        return context


class CategoryDetailView(View):
    template_name = "blog/catdetail.html"

    def get(self, request, slug_cat):
        categor = get_object_or_404(Category_blog, slug_cat=slug_cat)
        blog_list = Blogs.objects.filter(category=categor)
        categor_list = Category_blog.objects.all()
        paginator = Paginator(blog_list, 6)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)
        context = {
            "cat": categor,
            "blog_list": blog_list,
            "categor_list": categor_list,
            "bloglist": page_obj,
        }
        return render(request, "blog/catdetail.html", context)

shop/blog/templates/blog/blogdetail.html
{% extends "base.html" %}
{% load static %}
{% load jalali_tags %}
{% block title %}{{blogdetail.blog_name}}{% endblock title %}
{% block content %}

        <main class="cart-page default ">
            <div class="container">
                <div class="row">
                    <div class="single_blog_content col-12 col-lg-9 mx-auto order-1 order-sm-1 ">
                        <header class="card-header">
                            <h3 class="card-title"><span>{{blogdetail.blog_name}}</span></h3>
                        </header>
                        <div class="single_blog_page">

                            <div class="single_blog_box_content">
                                <form class="form-account">
                                    <div class="row">

                                        <div class="col-md-12 col-sm-12">

                                            <img src="{{blogdetail.blog_image.url}}" alt="{{blogdetail.blog_name}}" />
                                            <div class="data_det">
                                                <span class="publish_date">
                                                    <i class="fa fa-clock"></i>
                                                {{blogdetail.create_date|to_jalali:'%y/%m/%d | %H:%M:%S'}}
                                                </span>
                                                <span class="author">
                                                    <i class="fa fa-user-alt"></i>
                                                    ارسال شده توسط {{blogdetail.username}}
                                                </span>
                                                <span class="categoey">
                                                    <i class="fa fa-folder"></i>
                                                    {{blogdetail.category}}
                                                </span>
                                                <span class="visitors">
                                                    <i class="fa fa-eye"></i> 1725 بازدید
                                                </span>
                                            </div>
                                            <p>
                                             
                                                {{blogdetail.blog_description}}
                                            </p>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-lg-3">

                        <div class="sidebar_blog">
                            <div class="widget_blog">
                                <div class="widget_blog_headbox">
                                    <h3> دسته بندی ها </h3>
                                </div>
                                <div class="blog_list_widget_blog">
                                    <div class="widget_blog_groups">
                                        {% for category in categories %}
                                        <ul class="widget_blog_posts">
                                            <li><a class="widget_blog_title_link" href="{% url 'blog:category_detail' category.slug_cat %}">{{category.name}}</a></li>
                                        </ul>
                                        {% endfor %}
                                    </div>
                                </div><!-- end blog-list -->
                            </div>
                            <div class="widget_blog marg_top20">
                                <div class="widget_blog_headbox">
                                    <h3>آخرین مقالات </h3>
                                </div>
                                <div class="blog_list_widget_blog">
                                    <div class="widget_blog_groups">
                                        <ul class="widget_blog_posts">
                                            <li><a class="widget_blog_title_link" href=""> این‌ بار هوش مصنوعی، تصاویری از کارخانه تولید عروس دریایی را افشا می‌کند!</a></li>
                                            <li><a class="widget_blog_title_link" href="">  خط سفید روی نمایشگر گلکسی A71 سامسونگ؛ ماجرا چیست؟</a></li>
                                            <li><a class="widget_blog_title_link" href="">بهترین گوشی های مناسب عکاسی در بازار ایران</a></li>
                                            <li><a class="widget_blog_title_link" href="">هزینه ساخت بازی‌های انحصاری پلی استیشن با فیلم‌های بلاک‌باستر برابری می‌کند</a></li>
                                            <li><a class="widget_blog_title_link" href=""> یک دهه سکوت شکست؛ مایکروسافت آمار فروش ایکس باکس را فاش کرد!</a></li>
                                            <li><a class="widget_blog_title_link" href="">  بررسی تلویزیون 4K اسنوا؛ ۵۵ اینچی اقتصادی برای فیلم‌بازها!</a></li>
                                        </ul>
                                    </div>
                                </div><!-- end blog-list -->
                            </div>

                        </div>
                    </div>
                </div>
            </div>

        </main>
{% endblock content %}

shop/blog/templates/blog/catdetail.html
{% extends "base.html" %}
{% load static %}
{% load jalali_tags %}
{% block title %}وبلاگ ها{% endblock title %}
{% block content %}

        <main class="category-blog default space-top-30">
            <div class="container ">
               
                <div class="row">
                    <div class="col-12">
                        <nav>
                            <ul class="breadcrumb">
                                <a href="{% url 'home:home1' %}">
                                <li>
                                    <i class="fa fa-home" aria-hidden="true"></i>
                                </li>
                                </a>

                                <li>
                                    <a href="#"><span>بلاگ</span></a>
                                </li>
                                <a href="{% url 'blog:bloglist1' %}">
                                    <li>
                                        <span>همه وبلاگ ها  </span>
                                    </li>
                                </a>
                            </ul>
                        </nav>
                    </div>
                    <div class="single_blog_content cat_blog_content col-12 col-lg-9 mx-auto order-1 order-sm-1 ">
                        <div class="row listing-items Blog-category">
                            {% for blog in bloglist %}
                            <div class="col-xl-6 col-lg-6 col-md-6 col-12  ">
                                <div class="blog_tag">
                                    <a href="{% url 'blog:blogdetail1' blog.slug %}">
                                        <img src="{{blog.blog_image.url}}" class="img-fluid" alt="">
                                    </a>
                                    <a href="{% url 'blog:blogdetail1' blog.slug %}">
                                        <h2 class="Blog_title">
                                            {{blog.blog_description|truncatewords:10}}
                                        </h2>
                                    </a>
                                    <div class="Blog_list">
                                        <span class="Blog_author">
                                            <i class="fa fa-user"></i>
                                            {{blog.username}}
                                        </span>
                                        <span class="Blog_Date">
                                            <i class="fa fa-calendar "></i>
                                           {{ blog.create_date|to_jalali:'%y/%m/%d | %H:%M:%S'}}
                                        </span>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}         
                        </div>
                         <div class="row">
                                        <div class="col-sm-9 padding-right">
                                            <ul class="pagination">
                                                {% if bloglist.paginator.count != 0 %}
                                                    {% if bloglist.has_previous %}
                                                        <li class="page-item"> 
                                                            <a href="?page={{bloglist.previous_page_number}}" class="page-link">&laquo;</a> 
                                                        </li>
                                                    {% else %}
                                                        <li class="page-item disabled"> 
                                                            <a class="page-link">&laquo;</a> 
                                                        </li>
                                                    {% endif %}

                                                    {% for i in bloglist.paginator.page_range %}
                                                        {% if bloglist.number == i %}
                                                            <li class="page-item active"> 
                                                                <a class="page-link">{{i}}</a> 
                                                            </li>
                                                        {% else %}
                                                            <li class="page-item "> 
                                                                <a href="?page={{i}}" class="page-link">{{i}}</a> 
                                                            </li>
                                                        {% endif %}
                                                    {% endfor %}

                                                    {% if bloglist.has_next %}
                                                        <li class="page-item"> 
                                                            <a href="?page={{bloglist.next_page_number}}" class="page-link">&raquo;</a> 
                                                        </li>
                                                    {% else %}
                                                        <li class="page-item disabled"> 
                                                            <a class="page-link">&raquo;</a> 
                                                        </li>
                                                    {% endif %}
                                                {% else %}
                                                    <h3 style="color:#46A9AE; padding:200px">وبلاگی وجود ندارد</h3>
                                                {% endif %}
                                            </ul>
                                        </div>
                                    </div>
                    </div>
                    <div class="col-12 col-lg-3 ">

                        <div class="sidebar_blog">
                            <div class="widget_blog">
                                <div class="widget_blog_headbox">
                                    <h3> دسته بندی ها </h3>
                                </div>
                                                 
                                <div class="blog_list_widget_blog">
  
                                    <div class="widget_blog_groups">
                                        {% for category in categor_list %}
                                        <ul class="widget_blog_posts">
                                            <li><a class="widget_blog_title_link" href="{% url 'blog:category_detail' category.slug_cat %}">{{category.name}}</a></li>
                                        </ul>
                                        {% endfor %}
                                    </div>
                         
                                </div><!-- end blog-list -->
                 
                            </div>
                            <div class="widget_blog marg_top20">
                                <div class="widget_blog_headbox">
                                    <h3>آخرین مقالات </h3>
                                </div>
                                <div class="blog_list_widget_blog">
                                    <div class="widget_blog_groups">
                                        <ul class="widget_blog_posts">
                                            <li><a class="widget_blog_title_link" href=""> این‌ بار هوش مصنوعی، تصاویری از کارخانه تولید عروس دریایی را افشا می‌کند!</a></li>
                                            <li><a class="widget_blog_title_link" href="">  خط سفید روی نمایشگر گلکسی A71 سامسونگ؛ ماجرا چیست؟</a></li>
                                            <li><a class="widget_blog_title_link" href="">بهترین گوشی های مناسب عکاسی در بازار ایران</a></li>
                                            <li><a class="widget_blog_title_link" href="">هزینه ساخت بازی‌های انحصاری پلی استیشن با فیلم‌های بلاک‌باستر برابری می‌کند</a></li>
                                            <li><a class="widget_blog_title_link" href=""> یک دهه سکوت شکست؛ مایکروسافت آمار فروش ایکس باکس را فاش کرد!</a></li>
                                            <li><a class="widget_blog_title_link" href="">  بررسی تلویزیون 4K اسنوا؛ ۵۵ اینچی اقتصادی برای فیلم‌بازها!</a></li>
                                        </ul>
                                    </div>
                                </div><!-- end blog-list -->
                            </div>

                        </div>
                    </div>
                    
                </div>
            </div>
        </main>

{% endblock content %}

                                   