shop/blog/urls.py
from django.urls import path, include
from blog.views import (
    BlogPageView,
    BlogDetailView,
    CategoryDetailView,
)

app_name = "blog"

urlpatterns = [
    path("", BlogPageView.as_view(), name="bloglist1"),
    path("<slug:slug>/", BlogDetailView.as_view(), name="blogdetail1"),
    path(
        "category/<slug:slug_cat>/",
        CategoryDetailView.as_view(),
        name="category_detail",
    ),
    # API
    path("api/v1/", include("blog.api.v1.urls")),
]

shop/cart/urls.py
from django.urls import path
from cart.views import (
    CartDetailView,
    AddCartView,
    CartDeleteView,
)

app_name = "cart"

urlpatterns = [
    path("", CartDetailView.as_view(), name="cart_detail"),
    path("add/<int:product_id>/", AddCartView.as_view(), name="cart_add"),
    path("remove/<int:product_id>/", CartDeleteView.as_view(), name="cart_remove"),
]

shop/home/urls.py
from django.urls import path
from home.views import (
    HomePageView,
    AboutPageView,
)

app_name = "home"

urlpatterns = [
    path("", HomePageView.as_view(), name="home1"),
    path("about-us", AboutPageView.as_view(), name="about1"),
]

shop/shop/urls.py
from django.urls import path, include
from shop.views import (
    ShopListView,
    ShopDetailView,
    SearchView,
    CategoryListView,
    CategoryDetailView,
    CheckOutView,
)

app_name = "shop"

urlpatterns = [
    path("", ShopListView.as_view(), name="shoplist"),
    path("search/", SearchView.as_view(), name="search1"),
    path("product/<slug:slug>/", ShopDetailView.as_view(), name="detailpro"),
    path("all-categories/", CategoryListView.as_view(), name="categorylist1"),
    path("<str:category_slug>/", CategoryDetailView.as_view(), name="categorydetail1"),
    path("payment/checkout/", CheckOutView.as_view(), name="checkout1"),
    path("api/v1/", include("shop.api.v1.urls")),
]

shop/shopproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from rest_framework_simplejwt.views import (
    # TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

schema_view = get_schema_view(
    openapi.Info(
        title="Massay API",
        default_version="v1",
        description="This is a Massay Api page",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="mehdipoladrag1382@gmail.com"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("admin/", admin.site.urls),
    # Doc Routs
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
   
    # Django Apps 
    path("", include("home.urls")),
    path("shop/", include("shop.urls")),
    path("accounts/", include("accounts.urls")),
    path("contact-us/", include("contact.urls")),
    path("blog/", include("blog.urls")),
    path("cart/", include("cart.urls")),
    path("admin-panel/", include("adminpanel.urls")),
    path("api-auth/", include("rest_framework.urls")),

    # Default Api Routs
    # path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/cart/forms.py
from django import forms

PRODUCT_COUNT_CHOICES = [(i, str(i)) for i in range(1, 10)]


class CartAddProductForm(forms.Form):
    product_count = forms.TypedChoiceField(
        choices=PRODUCT_COUNT_CHOICES, coerce=int, label="تعداد"
    )
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

shop/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View
from cart.forms import CartAddProductForm
from .cart import Cart
from shop.models import Product

# Create your views here.


class AddCartView(View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(
                product=product,
                product_count=cd["product_count"],
                update_count=cd["update"],
            )
        return redirect("cart:cart_detail")


class CartDeleteView(View):
    def get(self, request, product_id):
        cart = Cart(request)
        cart.remove(product_id)
        return redirect("cart:cart_detail")


class CartDetailView(View):
    def get(self, request):
        cart = Cart(request)
        if len(cart) == 0:
            return render(request, "cart/emptycart.html")
        else:
            for item in cart:
                item["update_product_count_form"] = CartAddProductForm(
                    initial={"product_count": item["product_count"], "update": True}
                )
            return render(request, "cart/cart_detail.html", {"cart": cart})

shop/cart/templates/cart/cart_detail.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block title %}سبد خرید{% endblock title %}
{% block content %}

        <main class="cart-page default space-top-30">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center">
                        <ul class="order-steps">
                            <li>
                                <a href="cart.html" class="active">
                                    <span>سبدخرید</span>
                                </a>
                            </li>
                            <li>
                                <a href="shopping-payment.html">
                                    <span>پرداخت</span>
                                </a>
                            </li>
                            <li>
                                <a href="successful-payment.html">
                                    <span>اتمام خرید و ارسال</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="cart_content col-xl-12 col-lg-12 col-md-12">
                        <header class="card-header">
                            <h3 class="card-title"><span>سبد خرید شما</span></h3>
                        </header>
                        <div class="table-responsive default">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col">محصول</th>
                                        <th scope="col">سبد خرید شما</th>
                                        <th scope="col">قیمت واحد</th>
                                        <th scope="col">تعداد</th>
                                        <th scope="col">قیمت نهایی</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in cart %}
                                        {% with product=item.product %}
                                    <tr class="cart_item">
                                        <td>
                                            <img src="{{item.product.pic.url}}" alt="">
                                            <a href="{% url 'cart:cart_remove' item.product.id %}"><i class="fa fa-times" aria-hidden="true"></i></a>
                                        </td>
                                        <td>
                                            <h3 class="cart_title">
                                               <a href="">
                                                   {{item.product.product_name}}
                                               </a>
                                            </h3>
                                            <div class="cart_content">
                                                <div><span>برند </span><span  class="item_property">{{item.product.product_brand}}</span></div>
                                                <span class="cart_divider"></span>
                                                <div><span>رنگ </span><span  class="item_property">{{item.product.product_color}}</span></div>
                                            </div>
                                        </td>
                                        <td>
                                            <div class="cart_price">
                                                {% if item.product.offer %}
                                                    <del><span>{{ item.product.price|floatformat:0|intcomma }}<span>تومان</span></span></del>
                                                    <ins><span>{{ item.product.discounted_price|floatformat:0|intcomma }}<span>تومان</span></span></ins>
                                                {% else %}
                                                   {{ item.product.price|floatformat:0|intcomma }} <span>تومان</span>
                                                {% endif %}
                                            </div>
                                        </td>
                                        <td>{{ item.product_count }}</td>
                                        {% if item.product.offer %}
                                            <td class="price_alltd">{{ item.discounted_price|floatformat:0|intcomma }} <span>تومان</span></td>
                                        {% else %}
                                            <td class="price_alltd">{{ item.price|floatformat:0|intcomma }} <span>تومان</span></td>
                                        {% endif %}
                                    </tr>
                                    {% endwith %}
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="cart-page-content col-xl-12 col-lg-12 col-md-12">
                        <div class="row cart_details">
                            
                            <div class="cart-page-content col-xl-8 col-lg-7 col-md-7 ">
                                <input type="text" placeholder="کد تخفیف" class="input_second input_all width-200" disabled>
                                <a href="#" class="btn btn-main-masai"> اعمال</a>
                                <a href="#" class="btn btn-second-masai">به روز رسانی</a>
                                <div class="text_details">
                                    <p>
                                        ارسال رایگان برای سفارش‌های بالای 1 میلیون و 400 هزار تومان
                                    </p>
                                    <p>
                                        افزودن کالا به سبد خرید به معنی رزرو آن نیست با توجه به محدودیت موجودی سبد خود را ثبت و خرید را تکمیل کنید.
                                    </p>
                                </div>
                            </div>
                            <div class="cart-page-aside col-xl-4 col-lg-5 col-md-5 divider_details">
                                <table class="table table_details">
                                    <tbody>
                                        <tr>
                                            <td>قیمت کل سفارش:</td>
                                            <td>5,398,000 <span>تومان</span></td>
                                        </tr>
                                        <tr>
                                            <td>بسته‌بندی و ارسال:</td>
                                            <td>وابسته به نوع ارسال</td>
                                        </tr>
                                        <tr class="all">
                                            <td>قیمت قابل پرداخت:</td>
                                            <td>{{ cart.get_total_price|floatformat:0|intcomma }} <span>تومان</span></td>
                                        </tr>
                                        <tr>
                                            <td colspan="2"><a href="{% url 'shop:checkout1' %}" class="btn big_btn btn-main-masai"> گام بعدی</a></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            </div>
                   </div>
                      
                    </div>
                    </div>
           
        </main>

{% endblock content %}

shop/cart/templates/cart/emptycart.html
{% extends "base.html" %}
{% load static %}
{% block title %}سبد خالی{% endblock title %}
{% block content %}
        <main class="cart default">
            <div class="container text-center cart_empty">

                <img src="{% static 'assets/img/empty-cart.png' %}" class="" />
                <h6>
                    سبد خرید شما در حال حاضر خالی است.

                </h6>
                <a href="{% url 'home:home1' %}" class="btn btn-main-masai">صفحه نخست</a>

            </div>
        </main>
{% endblock content %}