shop/blog/urls.py
from django.urls import path, include
from blog.views import (
    BlogPageView,
    BlogDetailView,
    CategoryDetailView,
)

app_name = "blog"

urlpatterns = [
    path("", BlogPageView.as_view(), name="bloglist1"),
    path("<slug:slug>/", BlogDetailView.as_view(), name="blogdetail1"),
    path(
        "category/<slug:slug_cat>/",
        CategoryDetailView.as_view(),
        name="category_detail",
    ),
    # API
    path("api/v1/", include("blog.api.v1.urls")),
]

shop/cart/urls.py
from django.urls import path
from cart.views import (
    CartDetailView,
    AddCartView,
    CartDeleteView,
)

app_name = "cart"

urlpatterns = [
    path("", CartDetailView.as_view(), name="cart_detail"),
    path("add/<int:product_id>/", AddCartView.as_view(), name="cart_add"),
    path("remove/<int:product_id>/", CartDeleteView.as_view(), name="cart_remove"),
]

shop/contact/urls.py
from django.urls import path, include
from contact.views import (
    ContactPageView,
)

app_name = "contact"

urlpatterns = [
    path("", ContactPageView.as_view(), name="contact1"),
    # API
    path("api/v1/", include("contact.api.v1.urls")),
]

shop/home/urls.py
from django.urls import path
from home.views import (
    HomePageView,
    AboutPageView,
)

app_name = "home"

urlpatterns = [
    path("", HomePageView.as_view(), name="home1"),
    path("about-us", AboutPageView.as_view(), name="about1"),
]

shop/shop/urls.py
from django.urls import path, include
from shop.views import (
    ShopListView,
    ShopDetailView,
    SearchView,
    CategoryListView,
    CategoryDetailView,
    CheckOutView,
)

app_name = "shop"

urlpatterns = [
    path("", ShopListView.as_view(), name="shoplist"),
    path("search/", SearchView.as_view(), name="search1"),
    path("product/<slug:slug>/", ShopDetailView.as_view(), name="detailpro"),
    path("all-categories/", CategoryListView.as_view(), name="categorylist1"),
    path("<str:category_slug>/", CategoryDetailView.as_view(), name="categorydetail1"),
    path("payment/checkout/", CheckOutView.as_view(), name="checkout1"),
    path("api/v1/", include("shop.api.v1.urls")),
]

shop/shopproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from rest_framework_simplejwt.views import (
    # TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

schema_view = get_schema_view(
    openapi.Info(
        title="Massay API",
        default_version="v1",
        description="This is a Massay Api page",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="mehdipoladrag1382@gmail.com"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path("admin/", admin.site.urls),
    # Doc Routs
    path(
        "swagger<format>/", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
   
    # Django Apps 
    path("", include("home.urls")),
    path("shop/", include("shop.urls")),
    path("accounts/", include("accounts.urls")),
    path("contact-us/", include("contact.urls")),
    path("blog/", include("blog.urls")),
    path("cart/", include("cart.urls")),
    path("admin-panel/", include("adminpanel.urls")),
    path("api-auth/", include("rest_framework.urls")),

    # Default Api Routs
    # path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/templates/partials/_footer.html
{% load static %}
   <footer class="main-footer default">
        <div class="back-to-top ">
            <a href="#">
                <span class="icon"><i class="fa fa-chevron-up"></i></span> <span>
                    بازگشت بالا
                </span>
            </a>
        </div>
        <div class=" servicesbg">
            <div class="footer-services container  space-10">
                <div class="row">
                    <div class="service-item col-2 contact-box text-center">
                        <img src="{% static 'assets/img/ico/png-4.png' %}" class="width-40" />
                        <span class="title-1 light-black">ضمانت اصل بودن</span>
                    </div>
                    <div class="service-item col-2 contact-box text-center">
                        <img src="{% static 'assets/img/ico/png-1.png' %}" class="width-40" />
                        <span class="title-1 light-black">پرداخت در محل</span>
                    </div>
                    <div class="service-item col-2 contact-box text-center">
                        <img src="{% static 'assets/img/ico/png-2.png' %}" class="width-40" />
                        <span class="title-1 light-black">ارسال سریع</span>
                    </div>
                    <div class="service-item col-2 contact-box text-center">
                        <img src="{% static 'assets/img/ico/png-5.png' %}" class="width-40" />
                        <span class="title-1 light-black">فرصت 7 روزه استرداد</span>
                    </div>
                    <div class="service-item col-2 contact-box text-center">
                        <img src="{% static 'assets/img/ico/png-3.png' %}" class="width-40" />
                        <span class="title-1 light-black">پشتیبانی تلفنی</span>
                    </div>
                    <div class="service-item col-2 contact-box text-center">
                        <img src="{% static 'assets/img/ico/png-7.png' %}" class="width-40" />
                        <span class="title-1 light-black">هدیه نقدی</span>
                    </div>
                   
                </div>
                
            </div>
        </div>
        <div class="container-fluid space-30 bg-map">
            
            <div class="footer-widgets container">
                <div class="row">
                    <div class="col-12 col-md-6 col-lg-3">
                        <div class="widget-menu widget card">
                            <div class="card-header">
                                <h3 class="card-title">درباره ما</h3>
                            </div>
                            <p class="about_footer">
                                قالب مَسای یک پکیج کامل ایرانی با هدف بی نهایت قالب HTML و WordPress و به روز رسانی همیشگی است، که تمام ویژگی های لازم طراحی سایت را در نظر میگیرد
                            </p>
                        </div>
                    </div>
                    <div class="col-12 col-md-6 col-lg-3">
                        <div class="widget-menu widget card">
                            <div class="card-header">
                                <h3 class="card-title">خدمات مشتریان</h3>
                            </div>
                            <ul class="footer-menu">
                                <li>
                                    <a href="#">ارسال فوری</a>
                                </li>
                                <li>
                                    <a href="#">پشتیبانی سریع</a>
                                </li>
                                <li>
                                    <a href="#">بازگشت وجه</a>
                                </li>
                                <li>
                                    <a href="#">بسته بندی کالا</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-12 col-md-6 col-lg-3">
                        <div class="widget-menu widget card">
                            <div class="card-header">
                                <h3 class="card-title">با مَسای شاپ</h3>
                            </div>
                            <ul class="footer-menu">
                          
                                <li>
                                    <a href="#">تامین کالا همکار</a>
                                </li>
                                <li>
                                    <a href="#">تخفیف سازمانی</a>
                                </li>
                                <li>
                                    <a href="{% url 'contact:contact1' %}">تماس با ما</a>
                                </li>
                                <li>
                                    <a href="{% url 'home:about1' %}">درباره ما</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-12 col-md-6 col-lg-3">
                        <div class="widget-menu widget card">
                            <div class="card-header">
                                <h3 class="card-title">مجوزات</h3>
                            </div>
                            <div class="License_img">
                                <a href="#" target="_blank"><img src="{% static 'assets/img/License_2.png' %}" alt=""></a>
                                <a href="#" target="_blank"><img src="{% static 'assets/img/License_1.png' %}" alt=""></a>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
          
        </div>
         
        <div class="copyright">
            <div class="container">
                <p>
                   این وب سایت به وسیله  <a href="#" target="_blank"> مهدی پولادرگ </a> پشتیبانی میشود.
                </p>
            </div>
        </div>
    </footer>

shop/templates/partials/_header.html
{% load static %}
{% load humanize %}

<div class="top-section fullscreen-container">
        <img src="{% static 'assets/img/banner_img/bg_top.jpg' %}" class="h-100">
    </div>
    <!--start mobile header -->
    <nav class="navbar direction-ltr fixed-top header-responsive">
        <div class="container">
            <div class="navbar-translate">

                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                        data-target="#navigation" aria-controls="navigation-index" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-bar bar1"></span>
                    <span class="navbar-toggler-bar bar2"></span>
                    <span class="navbar-toggler-bar bar3"></span>
                </button>
                <div class="search-nav default">
                    <form method="GET" action="{% url 'shop:search1' %}">
                        <input type="text" name="q" placeholder="جستجو ...">
                        <button type="submit">
                            <img src="{% static 'assets/img/search.png' %}" alt="جستجو">
                        </button>
                    </form>
                    <ul>
                        
                        {% if not user.is_authenticated %}
                        <li><a href="{% url 'accounts:signin1' %}"><i class="fa fa-sign-in colormain" aria-hidden="true"></i></a></li>
                        
                        {% else %}
                            <li><a href="{% url 'accounts:profile1' %}"><i class="fa-regular fa-user colormain" aria-hidden="true"></i></a></li>
                            <li><a href="{% url 'accounts:logout' %}" class="list__link"><i class="fa fa-sign-out icon-icon icon-color-1" aria-hidden="true"></i></a></li>
                        {% endif %}
                        {% comment %} <li><a href="#"><i class="fa fa-cart-arrow-down colormain" aria-hidden="true"></i></a></li> {% endcomment %}
                        
                    </ul>
                </div>
            </div>
            <div class="collapse navbar-collapse justify-content-end" id="navigation">
                <div class="logo-nav-res default text-center">
                    <a href="{% url 'home:home1' %}">
                        <img src="{% static 'assets/img/logo.png' %}"  alt="مسای شاپ">
                    </a>
                </div>
                <ul class="navbar-nav default">
                    <li>
                        <a href="{% url 'shop:shoplist' %}">فروشگاه</a>
                    </li>
                    <li>
                        <a href="{% url 'shop:categorylist1' %}">تمام دسته بندی ها</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:bloglist1' %}">وبلاگ ها</a>
                    </li>
                    <li>
                        <a href="{% url 'contact:contact1' %}">تماس با ما</a>
                    </li>
                    <li>
                        <a href="{% url 'home:about1' %}">درباره ما</a>
                    </li>
                    <li>
                        <a href="{% url 'accounts:signup1' %}">ثبت نام</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    <!-- end mobile header -->
    <div class="wrapper default">

        <!--start pc header -->
        <header class="Masai-header default">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-2 col-md-3 col-sm-4 col-5">
                        <div class="logo-area default">
                            <a href="{% url 'home:home1' %}">
                                <img src="{% static 'assets/img/logo.png' %}" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-8 col-md-5 col-sm-8 col-7">
                        <div class="search-area default">
                            <form method="GET" action="{% url 'shop:search1' %}" class="search"> 
                            <input type="text" name="q" placeholder="جستجو ...">
                            <button type="submit">
                            <img src="{% static 'assets/img/search.png' %}" alt="جستجو">
                            </button>
                        </form>
                        </div>
                    </div>
                    <div class="col-md-2 col-sm-12">
                        
   

                
                    {% if not user.is_authenticated %}
                        <div class="user_head">
                            <a href="{% url 'accounts:signin1' %}" class="iconhead">
                                <i class="fa fa-sign-in font-20" aria-hidden="true"></i>
                            </a>
                        </div>
                    {% else %}
                        <div class="user_head">
                            <li class="list_style">
                                <a href="{% url 'accounts:profile1' %}" class="iconhead">           
                                    <i class="fa fa-user icon-icon icon-color-1" aria-hidden="true">
                                        <span>پروفایل </span>
                                    </i> 
                                </a>
                            </li>
                        </div>
                    {% endif %}
                    

                        
                        <div class="cart dropdown masai_dropdown">
                            <span class="divider"></span>

                            <a href="#" class="dropdown-toggle iconhead" data-toggle="dropdown" id="navbar_a">
                                <i class="fa fa-cart-arrow-down font-20" aria-hidden="true"></i>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbar_a">
                                <div class="m_cart-header">
                                    <div class="m_cart-total">
                                        
                                    </div>
                                </div>
                                <div class="btn_cart">
                                    <a href="{% url 'cart:cart_detail' %}" class="btn btn_sabad">مشاهده سبد</a>
                                    <a href="Final-payment.html" class="btn btn_pardakht btn-main-masai">پرداخت</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <nav class="nav_header">
                <ul class="nav__ullist">
                    <li class="list_style">
                        <i class="fa fa-home icon-icon" aria-hidden="true"></i><a href="{% url 'home:home1' %}" class="list__link">صفحه اصلی</a>
                    </li>
                    <li class="list_style">
                        <i class="fa fa-shop icon-icon" aria-hidden="true"></i><a href="{% url 'shop:shoplist' %}" class="list__link">فروشگاه</a>
                    </li>
                    <li class="list_style">
                        <i class="fa fa-list-alt icon-icon" aria-hidden="true"></i><a href="{% url 'shop:categorylist1' %}" class="list__link">
                            دسته بندی محصولات
                        </a>
                    </li>
                    <li class="list_style">
                        <i class="fa fa-newspaper icon-icon" aria-hidden="true"></i>
                        <a href="{% url 'blog:bloglist1' %}" class="list__link">وبلاگ ها</a>
                    </li>
                    
                    <li class="list_style">
                        <i class="fa fa-phone icon-icon" aria-hidden="true"></i>
                        <a href="{% url 'contact:contact1' %}" class="list__link">تماس با ما</a>
                    </li>

                    <li class="list_style">
                        <i class="fa-solid fa-address-card" style="color:#46A9AE;" aria-hidden="true"></i>
                        <a href="{% url 'home:about1' %}" class="list__link">درباره ما</a>
                    </li>
                    {% if user.is_authenticated %}
                    <ul class="nav_header-2">
                        <li class="list_style">
                            <a href="{% url 'accounts:logout' %}" class="list__link">
                            <i class="fa fa-sign-out icon-icon icon-color-1" aria-hidden="true">   <span>خروج</span>   </i>
                            </a>
                        </li>
                    </ul>
                    {% else %}    
                     <ul class="nav_header-2">
                        <li class="list_style">
                            <a href="{% url 'accounts:signup1' %}" class="list__link">
                            <i class="fa fa-user-plus icon-icon icon-color-1" aria-hidden="true"></i>
                            </a>
                        </li>
                    </ul>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <!-- end pc header -->

shop/templates/partials/_message.html
<style>
.success-msg,
.error-msg {
    display: inline-block;
    margin: 0.5em 0;
    padding: 0.5em;
    border-radius: 3px;
    position: fixed;
    bottom: 20px;
    right: 20px;
    z-index: 1000;
    transition: opacity 0.5s ease-out;
}

.success-msg {
    color: #270;
    background-color: #DFF2BF;
}

.error-msg {
    color: #D8000C;
    background-color: #FFBABA;
}
</style>
{% if messages %}
    {% for msg in messages %}
      {% if msg.tags == 'error' %}
      <div class="error-msg">
        <i class="fa fa-times-circle"></i>
        {{ msg }}
      </div>
      {% else %}
      <div class="success-msg">
        <i class="fa fa-check"></i>
          {{ msg }}
      </div>
    {% endif %}
  {% endfor %}
{% endif %}


<script>
setTimeout(function() {
  var successMessageBox = document.querySelector(".success-msg");
  var errorMessageBox = document.querySelector(".error-msg");

  if (successMessageBox) {
    successMessageBox.style.opacity = "0";
    setTimeout(function() {
      successMessageBox.style.display = "none";
    }, 5000);
  }

  if (errorMessageBox) {
    errorMessageBox.style.opacity = "0";
    setTimeout(function() {
      errorMessageBox.style.display = "none";
    }, 5000);
  }
}, 2000);
</script>
{% if form.errors %}
  <div class="error-msg">
    <i class="fa fa-times-circle"></i>
    {% for field in form %}
      {% for error in field.errors %}
        {{ error }}
      {% endfor %}
    {% endfor %}
  </div>
{% endif %}

shop/templates/partials/_profile.html
{% load static %}


    <ul class="profile-menu-items">

        <li>
            <a href="{% url 'accounts:order1' %}" class="dropdown-item">
                <i class="fa fa-cart-arrow-down colormain" aria-hidden="true"></i>
                لیست سفارشات من
            </a>
        </li>
        <li>
            <a href="{% url 'accounts:address1' %}" class="dropdown-item">
                <i class="fa fa-map icon-icon colormain" aria-hidden="true"></i>
                آدرس ها
            </a>
        </li>

        <li>
            <a href="{% url 'accounts:profile1' %}" class="dropdown-item active">
                <i class="fa fa-user-large colormain"></i>
                پروفایل
            </a>
        </li>
        <li>
            <a href="{% url 'accounts:update1' %}" class="dropdown-item">
                <i class="fa fa-pencil colormain" aria-hidden="true"></i>
                ویرایش اطلاعات
            </a>
        </li>
        <li>
            <a href="{% url 'accounts:change1' %}" class="dropdown-item">
                <i class="fa fa-shield colormain" aria-hidden="true"></i>
                امنیت و تغییر رمز
            </a>
        </li>
        
    </ul>